// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:ddf6f269-5cb6-4797-b54f-1e0d510e027d",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_6E1QYHwoQ",
    "aws_user_pools_web_client_id": "236o6fdk4v3u62fnfikrg52v7c",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://m7obpdlc4bhgjizfddmzllzywa.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
